spring:
  port: ${8080:PORT}
  config:
    activate:
      on-profile: dev
  application:
    name: spring-lms
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:lmsdb}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_USER:supersecretpassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    