spring:
  application:
    name: spring-lms
  profiles:
    active: dev

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  ## Liquibase
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: lmsdb


## JWT Secret key & Expiration
jwt:
  access:
    secret: ${JWT_ACCESS_SECRET}
    expiration: ${JWT_ACCESS_EXPIRATION:30m}
  refresh:
    secret: ${JWT_REFRESH_SECRET}
    expiration: ${JWT_REFRESH_EXPIRATION:1d}


resilience4j:
  ratelimiter:
    configs:
      default:
        limit-for-period: 100
        limit-refresh-period: 60s
        timeout-duration: 1500ms
        register-health-indicator: false
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
    instances:
      rabbitmq-publish:
        base-config: default

server:
  forward-headers-strategy: FRAMEWORK
